### ISSUE TITLE
Invalid packages

### ISSUE THREAD

**Issue by jeroen** [devOpifex/devOpifex.r-universe.dev#1]
There are several invalid entries in your registry. Can you have a look at the logs: https://github.com/r-universe/devopifex/actions/workflows/sync.yml

One line has `"package": "ambiorix/surf"` which is incorrect. The `package` field should match the name of the R package and is not allowed to have slashes.

Another entry https://github.com/devOpifex/artifex seems 404.

**Comment by JohnCoene** [comment]
Thanks! I forgot I transferred all these repos to https://github.com/ambiorix-web/, just removed them.
